language: java
jdk:
  - openjdk17

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - fruitsjh@gmail.com